name: Run Django Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt --break-system-packages

      - name: Make migrations
        run: |
          python3 manage.py makemigrations students

      - name: Apply migrations
        run: |
          python3 manage.py migrate

      - name: Run tests
        run: |
          python manage.py test
